test_for_cortex/urls.py
from django.contrib import admin
from django.urls import path
from staff import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.views_staff, name='view_all'),
    path('add/', views.add_employee, name='add_employee'),
    path('edit/<int:employee_id>/', views.edit_employee, name='edit_employee'),
    path('delete/<int:employee_id>/', views.delete_employee, name='delete_employee'),
    path('add_position/', views.add_position, name='add_position'),
    path('positions/', views.positions_list, name='positions_list'),
    path('edit_position/<int:position_id>/', views.edit_position, name='edit_position'),
    path('delete_position/<int:position_id>/', views.delete_position, name='delete_position'),
    path('search/', views.search, name='search'),
]

staff/models.py
from django.db import models
from django.utils import timezone


class Position(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Должность"
        verbose_name_plural = 'Должности'


class Staff(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    date_except = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.name} {self.surname} {self.last_name}"

    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = 'Сотрудники'

staff/forms.py
from django import forms
from .models import Staff, Position

class addStaff(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['name', 'surname', 'last_name', 'position', 'date_except']



class EmployeeEditForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['name', 'surname', 'last_name', 'position', 'date_except']


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = ['title']

staff/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import addStaff, EmployeeEditForm, PositionForm
from .models import Staff, Position
from django.db.models import Q

def search(request):
    query = request.GET.get('q')
    employees = Staff.objects.filter(
        Q(name__icontains=query) | Q(surname__icontains=query) | Q(last_name__icontains=query) | Q(
            position__title__icontains=query)
    )
    positions = Position.objects.filter(title__icontains=query)

    return render(request, 'search_results.html', {'employees': employees, 'positions': positions, 'query': query})
def delete_employee(request, employee_id):
    employee = get_object_or_404(Staff, id=employee_id)
    if request.method == 'POST':
        employee.delete()
        return redirect('view_all')
def add_employee(request):
    if request.method == 'POST':
        form = addStaff(request.POST)
        if form.is_valid():
            form.save()
            return redirect('view_all')  # Перенаправление на страницу со списком сотрудников
    else:
        form = addStaff()

    return render(request, 'add_staff.html', {'form': form})


def views_staff(request):
    context = Staff.objects.all()
    return render(request, 'view_all.html', {'context': context})


def edit_employee(request, employee_id):
    employee = get_object_or_404(Staff, id=employee_id)

    if request.method == 'POST':
        form = EmployeeEditForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('view_all')
    else:
        form = EmployeeEditForm(instance=employee)

    return render(request, 'edit_employee.html', {'form': form})


# Position

def add_position(request):
    if request.method == 'POST':
        form = PositionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('positions_list')  # Перенаправление на страницу со списком должностей
    else:
        form = PositionForm()

    return render(request, 'add_position.html', {'form': form})

def positions_list(request):
    positions = Position.objects.all()
    return render(request, 'positions_list.html', {'positions': positions})

def edit_position(request, position_id):
    position = get_object_or_404(Position, id=position_id)

    if request.method == 'POST':
        form = PositionForm(request.POST, instance=position)
        if form.is_valid():
            form.save()
            return redirect('positions_list')  # Перенаправление на страницу со списком должностей
    else:
        form = PositionForm(instance=position)

    return render(request, 'edit_position.html', {'form': form})

def delete_position(request, position_id):
    position = get_object_or_404(Position, id=position_id)
    if request.method == 'POST':
        position.delete()
        return redirect('positions_list')

staff/templates/add_position.html
{% extends 'base.html' %}
{% block title %}Добавить должность{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h1>Добавить должность</h1>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Название должности</label>
          <br>
            {{ form.title }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

staff/templates/add_staff.html
{% extends 'base.html' %}

{% block title %}Добавить сотрудника{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>Добавление сотрудника</h1>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Имя</label>
            <br>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="id_surname">Отчество</label>
            <br>
            {{ form.surname }}
        </div>
        <div class="form-group">
            <label for="id_last_name">Фамилия</label>
            <br>
            {{ form.last_name }}
        </div>
        <div class="form-group">
            <label for="id_position">Должность</label>
            <br>
            {{ form.position }}
        </div>
        <div class="form-group">
            <label for="id_date_except">Дата приема на работу</label>
            <br>
            {{ form.date_except }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

staff/templates/edit_employee.html
{% extends 'base.html' %}

    <title>{% block title %}Добавить сотрудника{% endblock %}</title>

{% block content %}
<h1>Edit Employee</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

staff/templates/edit_position.html
{% extends 'base.html' %}
{% block title %}Редактировать должность{% endblock %}

{% block content %}
  <h1>Редактировать должность</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

staff/templates/positions_list.html
{% extends 'base.html' %}
{% block title %}Главная - просмотр всех должностей{% endblock %}
{% block content %}
    <h1>Просмотр всех должностей</h1>
    <table border="1">
        <thead>
        <tr>
            <th>Название должности</th>
            <th>Действие</th>
            <th>Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for position in positions %}
        <tr>
            <td>{{ position.title }}</td>
            <td><a href="{% url 'edit_position' position_id=position.id %}">Редактировать</a></td>
            <td>
                <form method="post" action="{% url 'delete_position' position_id=position.id %}">
                    {% csrf_token %}
                    <input  type="submit" value="Удалить">
                </form>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'add_position' %}">Добавить должность</a>
    <div>
        <h1>Каталог сотрудников</h1>
        <a href="{% url 'view_all' %}">Просмотр всех сотрудников</a>
    </div>
{% endblock %}

staff/templates/search_results.html
{% extends 'base.html' %}

{% block title %}Результаты поиска{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h1>Результаты поиска</h1>

    <div class="mt-4">
      <h2>Сотрудники:</h2>
      <ul class="list-group">
        {% for employee in employees %}
          <li class="list-group-item">{{ employee.name }} {{ employee.surname }} {{ employee.last_name }} - {{ employee.position }}</li>
        {% empty %}
          <li class="list-group-item text-muted">Ничего не найдено</li>
        {% endfor %}
      </ul>
    </div>

    <div class="mt-4">
      <h2>Должности:</h2>
      <ul class="list-group">
        {% for position in positions %}
          <li class="list-group-item">{{ position.title }}</li>
        {% empty %}
          <li class="list-group-item text-muted">Ничего не найдено</li>
        {% endfor %}
      </ul>
    </div>

    <p class="mt-4">Ваш запрос: "{{ query }}"</p>
  </div>
{% endblock %}

staff/templates/view_all.html
{% extends 'base.html' %}
{% block title %}Главная - просмотр всех сотрудников{% endblock %}
{% block content %}
<h1>Просмотр всех сотрудников</h1>
<table border="1">
    <thead>
    <tr>
        <th>Имя</th>
        <th>Отчество</th>
        <th>Фамилия</th>
        <th>Должность</th>
        <th>Дата приема на работу</th>
        <th>Действие</th>
        <th>Удалить</th>
    </tr>
    </thead>
    <tbody>
    {% for employee in context %}
    <tr>
        <td>{{ employee.name }}</td>
        <td>{{ employee.surname }}</td>
        <td>{{ employee.last_name }}</td>
        <td>{{ employee.position }}</td>
        <td>{{ employee.date_except }}</td>
        <td><a href="{% url 'edit_employee' employee_id=employee.id %}">Редактировать</a></td>
        <td>
            <form method="post" action="{% url 'delete_employee' employee_id=employee.id %}">
                {% csrf_token %}
                <input type="submit" value="Удалить">
            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{% url 'add_employee' %}">Добавить сотрудника</a>
<div>
    <h1>Каталог должностей</h1>

    <a href="{% url 'positions_list' %}">Добавить сотрудника</a>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        body {
            display: flex;
            flex-direction: column;
        }

        header {
            flex-shrink: 0; /* Хедер не будет растягиваться */
        }

        .content {
            flex-grow: 1; /* Контент будет занимать оставшееся пространство */
        }

        footer {
            flex-shrink: 0; /* Футер не будет растягиваться */
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'view_all' %}">Главная</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_employee' %}">Добавить сотрудника</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'positions_list' %}">Должности</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_position' %}">Добавить должность</a>
                    </li>
                    <li class="nav-item">
                        <form class="form-inline mt-1" method="GET" action="{% url 'search' %}">
                            <div class="input-group">
                                <input type="text" class="form-control" name="q" placeholder="Поиск...">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-primary">Искать</button>
                                </div>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}
<footer class="footer mt-auto py-3 bg-dark text-white">
    <div class="container text-center">
        <span class="text-muted">Тестовое задание в Cortex &copy; 2023</span>
        <!-- Другая информация в футере, ссылки, контактные данные и т.д. -->
    </div>
</footer>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>